package by.betrayal.personalservice.exception;

public class NotFoundException extends RuntimeException{
}
